### ISSUE TITLE
Problema com o back-end após a atualização.

### ISSUE THREAD

**Issue by cristopherybd** [ronandesign/whaticket-saas#6]
Bom dia, atualizei minha instância para a versão mais recente do software, mas agora que tento iniciar o backend ocorre um erro:

deploy@crm:~/yourbestdev/backend$ npm start

> backend@1.0.0 start
> nodemon dist/server.js

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node dist/server.js`
node:internal/modules/cjs/loader:435
      throw err;
      ^

Error: Cannot find module '/home/deploy/yourbestdev/backend/node_modules/cache-manager/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:427:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:640:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1014:27)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/deploy/yourbestdev/backend/node_modules/@whiskeysockets/baileys/lib/Store/make-cache-manager-store.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/deploy/yourbestdev/backend/node_modules/@whiskeysockets/baileys/lib/Store/index.js:7:52)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/deploy/yourbestdev/backend/node_modules/@whiskeysockets/baileys/lib/index.js:26:14)
    at Module._compile (node:internal/modules/cjs/loader:1198:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/deploy/yourbestdev/backend/node_modules/cache-manager/package.json',
  requestPath: 'cache-manager'
}
[nodemon] app crashed - waiting for file changes before starting...

Eu apreciaria sua ajuda, obrigado.

**Comment by cristopherybd** [comment]
Encontrei a solução em https://github.com/WhiskeySockets/Baileys/issues/505
